spring.application.name=Ecomm
server.port=8082
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/testdb_dev
spring.datasource.username=dev
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
app.environment=DEV
management.endpoints.web.exposure.include=*

management.info.env.enabled=true
info.app,name=Ecommerce Backend
info.app.version=1.0
info.app.description=SpringBoot Learning Project